name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/cachix-action@v10
        with:
          name: haskell-org
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Site
        # we run the checks as a separate step
        run: nix build -f . built -o built-site --arg doCheck false

      - name: Check Links
        run: nix run --quiet -f . linkchecker -c linkchecker built-site

      - uses: actions/upload-artifact@v2
        with:
          name: www.haskell.org
          path: built-site*  # Uses glob pattern because
                             # actions/upload-artifact@v2 gets
                             # confused by symlinks otherwise
                             #
                             # See:
                             # https://github.com/actions/upload-artifact/issues/92
